// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentMeetingPlanner.Data;

#nullable disable

namespace SacramentMeetingPlanner.Migrations
{
    [DbContext(typeof(SacramentMeetingPlannerContext))]
    partial class SacramentMeetingPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("SacramentMeetingPlanner.Models.Plan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("benediction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("closingHymnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("closingHymnNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("conducting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dismissalSongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dismissalSongNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("invocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("president")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sacramentHymnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sacramentHymnNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("special")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("SacramentMeetingPlanner.Models.Speaker", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("planId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Speaker");
                });
#pragma warning restore 612, 618
        }
    }
}
